-- Booking Prototipo · RDA 1
-- Ejecutar una sola vez en un proyecto nuevo de Supabase.
BEGIN;
CREATE TABLE IF NOT EXISTS "users" (
  "id" TEXT PRIMARY KEY,
  "email" TEXT NOT NULL UNIQUE,
  "name" TEXT NOT NULL,
  "passwordHash" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "createdAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "sessions" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "expiresAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "cities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "country" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "chains" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "accommodations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" TEXT NOT NULL,
  "cityId" INTEGER NOT NULL,
  "destino" TEXT NOT NULL,
  "descripcion" TEXT NOT NULL,
  "direccion" TEXT NOT NULL,
  "tipo" TEXT NOT NULL,
  "image" TEXT NOT NULL,
  "published" BOOLEAN NOT NULL,
  "createdAt" TEXT NOT NULL,
  "updatedAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "room_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "accommodationId" INTEGER NOT NULL,
  "nombre" TEXT NOT NULL,
  "capacidadAdultos" INTEGER NOT NULL,
  "capacidadNinos" INTEGER NOT NULL,
  "habitaciones" INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "rate_plans" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "roomTypeId" INTEGER NOT NULL,
  "precioPorNoche" NUMERIC(10,2) NOT NULL,
  "currency" TEXT NOT NULL,
  "cancellation" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "facilities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "accommodation_facilities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "accommodationId" INTEGER NOT NULL,
  "facilityId" INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "photos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "accommodationId" INTEGER NOT NULL,
  "url" TEXT NOT NULL,
  "caption" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "accommodationId" INTEGER NOT NULL,
  "author" TEXT NOT NULL,
  "score" INTEGER NOT NULL,
  "comment" TEXT NOT NULL,
  "createdAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "availability_products" (
  "id" TEXT PRIMARY KEY,
  "accommodationId" INTEGER NOT NULL,
  "checkin" TEXT NOT NULL,
  "checkout" TEXT NOT NULL,
  "guests" TEXT NOT NULL,
  "total" NUMERIC(12,2) NOT NULL,
  "expiresAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "quotes" (
  "id" TEXT PRIMARY KEY,
  "productId" TEXT NOT NULL,
  "ownerId" TEXT NOT NULL,
  "total" NUMERIC(12,2) NOT NULL,
  "expiresAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "orders" (
  "id" TEXT PRIMARY KEY,
  "accommodationId" INTEGER NOT NULL,
  "ownerId" TEXT NOT NULL,
  "quoteId" TEXT NOT NULL UNIQUE,
  "locator" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "checkin" TEXT NOT NULL,
  "checkout" TEXT NOT NULL,
  "guests" TEXT NOT NULL,
  "total" NUMERIC(12,2) NOT NULL,
  "currency" TEXT NOT NULL,
  "paymentReference" TEXT NOT NULL,
  "customer" TEXT NOT NULL,
  "createdAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "order_guests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "age" INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "idempotency_keys" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "operation" TEXT NOT NULL,
  "fingerprint" TEXT NOT NULL,
  "response" TEXT NOT NULL,
  "createdAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "outbox_events" (
  "id" TEXT PRIMARY KEY,
  "eventType" TEXT NOT NULL,
  "resourceId" TEXT NOT NULL,
  "timestamp" TEXT NOT NULL,
  "data" TEXT NOT NULL,
  "status" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "webhook_subscriptions" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "url" TEXT NOT NULL,
  "events" TEXT NOT NULL,
  "secret" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "audit_logs" (
  "id" TEXT PRIMARY KEY,
  "actorId" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "resourceId" TEXT NOT NULL,
  "timestamp" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "transaction_lock" (
  "id" INTEGER PRIMARY KEY,
  "version" INTEGER NOT NULL
);
ALTER TABLE "sessions" ADD CONSTRAINT "fk_sessions_userId" FOREIGN KEY ("userId") REFERENCES "users" (id) ON DELETE RESTRICT;
ALTER TABLE "accommodations" ADD CONSTRAINT "fk_accommodations_cityId" FOREIGN KEY ("cityId") REFERENCES "cities" (id) ON DELETE RESTRICT;
ALTER TABLE "room_types" ADD CONSTRAINT "fk_room_types_accommodationId" FOREIGN KEY ("accommodationId") REFERENCES "accommodations" (id) ON DELETE RESTRICT;
ALTER TABLE "rate_plans" ADD CONSTRAINT "fk_rate_plans_roomTypeId" FOREIGN KEY ("roomTypeId") REFERENCES "room_types" (id) ON DELETE RESTRICT;
ALTER TABLE "accommodation_facilities" ADD CONSTRAINT "fk_accommodation_facilities_accommodationId" FOREIGN KEY ("accommodationId") REFERENCES "accommodations" (id) ON DELETE RESTRICT;
ALTER TABLE "accommodation_facilities" ADD CONSTRAINT "fk_accommodation_facilities_facilityId" FOREIGN KEY ("facilityId") REFERENCES "facilities" (id) ON DELETE RESTRICT;
ALTER TABLE "photos" ADD CONSTRAINT "fk_photos_accommodationId" FOREIGN KEY ("accommodationId") REFERENCES "accommodations" (id) ON DELETE RESTRICT;
ALTER TABLE "reviews" ADD CONSTRAINT "fk_reviews_accommodationId" FOREIGN KEY ("accommodationId") REFERENCES "accommodations" (id) ON DELETE RESTRICT;
ALTER TABLE "availability_products" ADD CONSTRAINT "fk_availability_products_accommodationId" FOREIGN KEY ("accommodationId") REFERENCES "accommodations" (id) ON DELETE RESTRICT;
ALTER TABLE "quotes" ADD CONSTRAINT "fk_quotes_productId" FOREIGN KEY ("productId") REFERENCES "availability_products" (id) ON DELETE RESTRICT;
ALTER TABLE "quotes" ADD CONSTRAINT "fk_quotes_ownerId" FOREIGN KEY ("ownerId") REFERENCES "users" (id) ON DELETE RESTRICT;
ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_accommodationId" FOREIGN KEY ("accommodationId") REFERENCES "accommodations" (id) ON DELETE RESTRICT;
ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_ownerId" FOREIGN KEY ("ownerId") REFERENCES "users" (id) ON DELETE RESTRICT;
ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_quoteId" FOREIGN KEY ("quoteId") REFERENCES "quotes" (id) ON DELETE RESTRICT;
ALTER TABLE "order_guests" ADD CONSTRAINT "fk_order_guests_orderId" FOREIGN KEY ("orderId") REFERENCES "orders" (id) ON DELETE RESTRICT;
ALTER TABLE "idempotency_keys" ADD CONSTRAINT "fk_idempotency_keys_ownerId" FOREIGN KEY ("ownerId") REFERENCES "users" (id) ON DELETE RESTRICT;
ALTER TABLE "webhook_subscriptions" ADD CONSTRAINT "fk_webhook_subscriptions_ownerId" FOREIGN KEY ("ownerId") REFERENCES "users" (id) ON DELETE RESTRICT;
ALTER TABLE "audit_logs" ADD CONSTRAINT "fk_audit_logs_actorId" FOREIGN KEY ("actorId") REFERENCES "users" (id) ON DELETE RESTRICT;

CREATE INDEX orders_availability_idx ON orders ("accommodationId", status, checkin, checkout);
CREATE INDEX orders_owner_idx ON orders ("ownerId");
CREATE INDEX outbox_pending_idx ON outbox_events (status, timestamp);
CREATE INDEX quotes_owner_idx ON quotes ("ownerId");
CREATE UNIQUE INDEX facility_link_unique ON accommodation_facilities ("accommodationId", "facilityId");
ALTER TABLE room_types ADD CONSTRAINT room_capacity CHECK ("capacidadAdultos" > 0 AND "capacidadNinos" >= 0 AND habitaciones > 0);
ALTER TABLE rate_plans ADD CONSTRAINT positive_rate CHECK ("precioPorNoche" > 0 AND currency = 'USD');
ALTER TABLE orders ADD CONSTRAINT valid_order CHECK (checkout > checkin AND total > 0 AND status IN ('CONFIRMED','CANCELLED','PENDING'));
ALTER TABLE users ADD CONSTRAINT valid_role CHECK (role IN ('admin','customer'));
ALTER TABLE reviews ADD CONSTRAINT valid_score CHECK (score BETWEEN 0 AND 10);
INSERT INTO transaction_lock (id,version) VALUES (1,0) ON CONFLICT DO NOTHING;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "users" FROM anon, authenticated;
ALTER TABLE "sessions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "sessions" FROM anon, authenticated;
ALTER TABLE "cities" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "cities" FROM anon, authenticated;
ALTER TABLE "chains" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "chains" FROM anon, authenticated;
ALTER TABLE "accommodations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "accommodations" FROM anon, authenticated;
ALTER TABLE "room_types" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "room_types" FROM anon, authenticated;
ALTER TABLE "rate_plans" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "rate_plans" FROM anon, authenticated;
ALTER TABLE "facilities" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "facilities" FROM anon, authenticated;
ALTER TABLE "accommodation_facilities" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "accommodation_facilities" FROM anon, authenticated;
ALTER TABLE "photos" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "photos" FROM anon, authenticated;
ALTER TABLE "reviews" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "reviews" FROM anon, authenticated;
ALTER TABLE "availability_products" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "availability_products" FROM anon, authenticated;
ALTER TABLE "quotes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "quotes" FROM anon, authenticated;
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "orders" FROM anon, authenticated;
ALTER TABLE "order_guests" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "order_guests" FROM anon, authenticated;
ALTER TABLE "idempotency_keys" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "idempotency_keys" FROM anon, authenticated;
ALTER TABLE "outbox_events" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "outbox_events" FROM anon, authenticated;
ALTER TABLE "webhook_subscriptions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "webhook_subscriptions" FROM anon, authenticated;
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "audit_logs" FROM anon, authenticated;
ALTER TABLE "transaction_lock" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "transaction_lock" FROM anon, authenticated;
COMMIT;

-- Renombrado sin eliminar datos: tablas y columnas en español.
BEGIN;
ALTER TABLE "users" RENAME TO "usuarios";
ALTER TABLE "usuarios" RENAME COLUMN "email" TO "correo";
ALTER TABLE "usuarios" RENAME COLUMN "name" TO "nombre";
ALTER TABLE "usuarios" RENAME COLUMN "passwordHash" TO "hash_contrasena";
ALTER TABLE "usuarios" RENAME COLUMN "role" TO "rol";
ALTER TABLE "usuarios" RENAME COLUMN "createdAt" TO "fecha_creacion";
ALTER TABLE "sessions" RENAME TO "sesiones";
ALTER TABLE "sesiones" RENAME COLUMN "userId" TO "usuario_id";
ALTER TABLE "sesiones" RENAME COLUMN "expiresAt" TO "fecha_expiracion";
ALTER TABLE "cities" RENAME TO "ciudades";
ALTER TABLE "ciudades" RENAME COLUMN "name" TO "nombre";
ALTER TABLE "ciudades" RENAME COLUMN "country" TO "pais";
ALTER TABLE "chains" RENAME TO "cadenas_hoteleras";
ALTER TABLE "cadenas_hoteleras" RENAME COLUMN "name" TO "nombre";
ALTER TABLE "accommodations" RENAME TO "alojamientos";
ALTER TABLE "alojamientos" RENAME COLUMN "cityId" TO "ciudad_id";
ALTER TABLE "alojamientos" RENAME COLUMN "image" TO "imagen";
ALTER TABLE "alojamientos" RENAME COLUMN "published" TO "publicado";
ALTER TABLE "alojamientos" RENAME COLUMN "createdAt" TO "fecha_creacion";
ALTER TABLE "alojamientos" RENAME COLUMN "updatedAt" TO "fecha_actualizacion";
ALTER TABLE "room_types" RENAME TO "tipos_habitacion";
ALTER TABLE "tipos_habitacion" RENAME COLUMN "accommodationId" TO "alojamiento_id";
ALTER TABLE "tipos_habitacion" RENAME COLUMN "capacidadAdultos" TO "capacidad_adultos";
ALTER TABLE "tipos_habitacion" RENAME COLUMN "capacidadNinos" TO "capacidad_ninos";
ALTER TABLE "rate_plans" RENAME TO "planes_tarifarios";
ALTER TABLE "planes_tarifarios" RENAME COLUMN "roomTypeId" TO "tipo_habitacion_id";
ALTER TABLE "planes_tarifarios" RENAME COLUMN "precioPorNoche" TO "precio_por_noche";
ALTER TABLE "planes_tarifarios" RENAME COLUMN "currency" TO "moneda";
ALTER TABLE "planes_tarifarios" RENAME COLUMN "cancellation" TO "politica_cancelacion";
ALTER TABLE "facilities" RENAME TO "servicios";
ALTER TABLE "servicios" RENAME COLUMN "name" TO "nombre";
ALTER TABLE "accommodation_facilities" RENAME TO "alojamientos_servicios";
ALTER TABLE "alojamientos_servicios" RENAME COLUMN "accommodationId" TO "alojamiento_id";
ALTER TABLE "alojamientos_servicios" RENAME COLUMN "facilityId" TO "servicio_id";
ALTER TABLE "photos" RENAME TO "fotos";
ALTER TABLE "fotos" RENAME COLUMN "accommodationId" TO "alojamiento_id";
ALTER TABLE "fotos" RENAME COLUMN "caption" TO "descripcion";
ALTER TABLE "reviews" RENAME TO "resenas";
ALTER TABLE "resenas" RENAME COLUMN "accommodationId" TO "alojamiento_id";
ALTER TABLE "resenas" RENAME COLUMN "author" TO "autor";
ALTER TABLE "resenas" RENAME COLUMN "score" TO "puntuacion";
ALTER TABLE "resenas" RENAME COLUMN "comment" TO "comentario";
ALTER TABLE "resenas" RENAME COLUMN "createdAt" TO "fecha_creacion";
ALTER TABLE "availability_products" RENAME TO "productos_disponibilidad";
ALTER TABLE "productos_disponibilidad" RENAME COLUMN "accommodationId" TO "alojamiento_id";
ALTER TABLE "productos_disponibilidad" RENAME COLUMN "checkin" TO "fecha_entrada";
ALTER TABLE "productos_disponibilidad" RENAME COLUMN "checkout" TO "fecha_salida";
ALTER TABLE "productos_disponibilidad" RENAME COLUMN "guests" TO "huespedes";
ALTER TABLE "productos_disponibilidad" RENAME COLUMN "expiresAt" TO "fecha_expiracion";
ALTER TABLE "quotes" RENAME TO "cotizaciones";
ALTER TABLE "cotizaciones" RENAME COLUMN "productId" TO "producto_id";
ALTER TABLE "cotizaciones" RENAME COLUMN "ownerId" TO "propietario_id";
ALTER TABLE "cotizaciones" RENAME COLUMN "expiresAt" TO "fecha_expiracion";
ALTER TABLE "orders" RENAME TO "reservas";
ALTER TABLE "reservas" RENAME COLUMN "accommodationId" TO "alojamiento_id";
ALTER TABLE "reservas" RENAME COLUMN "ownerId" TO "propietario_id";
ALTER TABLE "reservas" RENAME COLUMN "quoteId" TO "cotizacion_id";
ALTER TABLE "reservas" RENAME COLUMN "locator" TO "localizador";
ALTER TABLE "reservas" RENAME COLUMN "status" TO "estado";
ALTER TABLE "reservas" RENAME COLUMN "checkin" TO "fecha_entrada";
ALTER TABLE "reservas" RENAME COLUMN "checkout" TO "fecha_salida";
ALTER TABLE "reservas" RENAME COLUMN "guests" TO "huespedes";
ALTER TABLE "reservas" RENAME COLUMN "currency" TO "moneda";
ALTER TABLE "reservas" RENAME COLUMN "paymentReference" TO "referencia_pago";
ALTER TABLE "reservas" RENAME COLUMN "customer" TO "cliente";
ALTER TABLE "reservas" RENAME COLUMN "createdAt" TO "fecha_creacion";
ALTER TABLE "order_guests" RENAME TO "huespedes_reserva";
ALTER TABLE "huespedes_reserva" RENAME COLUMN "orderId" TO "reserva_id";
ALTER TABLE "huespedes_reserva" RENAME COLUMN "name" TO "nombre";
ALTER TABLE "huespedes_reserva" RENAME COLUMN "age" TO "edad";
ALTER TABLE "idempotency_keys" RENAME TO "claves_idempotencia";
ALTER TABLE "claves_idempotencia" RENAME COLUMN "ownerId" TO "propietario_id";
ALTER TABLE "claves_idempotencia" RENAME COLUMN "operation" TO "operacion";
ALTER TABLE "claves_idempotencia" RENAME COLUMN "fingerprint" TO "huella_solicitud";
ALTER TABLE "claves_idempotencia" RENAME COLUMN "response" TO "respuesta";
ALTER TABLE "claves_idempotencia" RENAME COLUMN "createdAt" TO "fecha_creacion";
ALTER TABLE "outbox_events" RENAME TO "eventos_pendientes";
ALTER TABLE "eventos_pendientes" RENAME COLUMN "eventType" TO "tipo_evento";
ALTER TABLE "eventos_pendientes" RENAME COLUMN "resourceId" TO "recurso_id";
ALTER TABLE "eventos_pendientes" RENAME COLUMN "timestamp" TO "fecha_evento";
ALTER TABLE "eventos_pendientes" RENAME COLUMN "data" TO "datos";
ALTER TABLE "eventos_pendientes" RENAME COLUMN "status" TO "estado";
ALTER TABLE "webhook_subscriptions" RENAME TO "suscripciones_webhook";
ALTER TABLE "suscripciones_webhook" RENAME COLUMN "ownerId" TO "propietario_id";
ALTER TABLE "suscripciones_webhook" RENAME COLUMN "events" TO "eventos";
ALTER TABLE "suscripciones_webhook" RENAME COLUMN "secret" TO "secreto";
ALTER TABLE "audit_logs" RENAME TO "registros_auditoria";
ALTER TABLE "registros_auditoria" RENAME COLUMN "actorId" TO "actor_id";
ALTER TABLE "registros_auditoria" RENAME COLUMN "action" TO "accion";
ALTER TABLE "registros_auditoria" RENAME COLUMN "resourceId" TO "recurso_id";
ALTER TABLE "registros_auditoria" RENAME COLUMN "timestamp" TO "fecha_evento";
ALTER TABLE "transaction_lock" RENAME TO "bloqueo_transacciones";
COMMIT;

BEGIN;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ciudades ADD COLUMN IF NOT EXISTS codigo TEXT NOT NULL DEFAULT '';
ALTER TABLE ciudades ADD COLUMN IF NOT EXISTS provincia TEXT NOT NULL DEFAULT '';
ALTER TABLE ciudades ADD COLUMN IF NOT EXISTS region TEXT NOT NULL DEFAULT '';
ALTER TABLE ciudades ADD COLUMN IF NOT EXISTS latitud DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE ciudades ADD COLUMN IF NOT EXISTS longitud DOUBLE PRECISION NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS ciudades_codigo_unico ON ciudades(codigo) WHERE codigo <> '';
CREATE TABLE IF NOT EXISTS categorias_gasto (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS gastos (id TEXT PRIMARY KEY, concepto TEXT NOT NULL, proveedor TEXT NOT NULL, categoria_id INTEGER NOT NULL REFERENCES categorias_gasto(id), alojamiento_id INTEGER REFERENCES alojamientos(id), importe NUMERIC(12,2) NOT NULL CHECK (importe > 0), fecha TEXT NOT NULL, estado TEXT NOT NULL CHECK (estado IN ('PENDIENTE','PAGADO')), notas TEXT NOT NULL, actor_id TEXT NOT NULL REFERENCES usuarios(id), fecha_creacion TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS gastos_fecha ON gastos(fecha);
ALTER TABLE categorias_gasto ENABLE ROW LEVEL SECURITY;
ALTER TABLE gastos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON categorias_gasto, gastos FROM anon, authenticated;
COMMIT;

BEGIN;
CREATE TABLE IF NOT EXISTS perfiles_usuario (usuario_id TEXT PRIMARY KEY REFERENCES usuarios(id), telefono TEXT NOT NULL DEFAULT '', documento TEXT NOT NULL DEFAULT '', direccion TEXT NOT NULL DEFAULT '', fecha_actualizacion TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS calendario_tarifas (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, alojamiento_id INTEGER NOT NULL REFERENCES alojamientos(id), fecha TEXT NOT NULL, precio NUMERIC(12,2) CHECK (precio > 0), cupo INTEGER CHECK (cupo >= 0), cerrado BOOLEAN NOT NULL DEFAULT FALSE, nota TEXT NOT NULL DEFAULT '', actor_id TEXT NOT NULL REFERENCES usuarios(id), fecha_actualizacion TEXT NOT NULL, UNIQUE(alojamiento_id,fecha));
CREATE TABLE IF NOT EXISTS facturas (id TEXT PRIMARY KEY, reserva_id TEXT NOT NULL UNIQUE REFERENCES reservas(id), usuario_id TEXT NOT NULL REFERENCES usuarios(id), numero TEXT NOT NULL UNIQUE, emisor TEXT NOT NULL, cliente TEXT NOT NULL, fecha_emision TEXT NOT NULL, subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0), impuestos NUMERIC(12,2) NOT NULL DEFAULT 0, total NUMERIC(12,2) NOT NULL CHECK (total >= 0), moneda TEXT NOT NULL DEFAULT 'USD', estado TEXT NOT NULL CHECK (estado IN ('EMITIDA','ANULADA')), version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS detalles_factura (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, factura_id TEXT NOT NULL REFERENCES facturas(id), descripcion TEXT NOT NULL, cantidad INTEGER NOT NULL CHECK (cantidad > 0), precio_unitario NUMERIC(12,2) NOT NULL CHECK (precio_unitario > 0), subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal > 0));
CREATE TABLE IF NOT EXISTS resenas_estancia (id TEXT PRIMARY KEY, reserva_id TEXT NOT NULL UNIQUE REFERENCES reservas(id), usuario_id TEXT NOT NULL REFERENCES usuarios(id), alojamiento_id INTEGER NOT NULL REFERENCES alojamientos(id), puntuacion INTEGER NOT NULL CHECK (puntuacion BETWEEN 1 AND 10), comentario TEXT NOT NULL, fecha_creacion TEXT NOT NULL, respuesta TEXT NOT NULL DEFAULT '', respondido_por TEXT REFERENCES usuarios(id), fecha_respuesta TEXT);
CREATE INDEX IF NOT EXISTS calendario_fecha ON calendario_tarifas(fecha);
CREATE INDEX IF NOT EXISTS resenas_estancia_alojamiento ON resenas_estancia(alojamiento_id);
ALTER TABLE perfiles_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendario_tarifas ENABLE ROW LEVEL SECURITY;
ALTER TABLE facturas ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalles_factura ENABLE ROW LEVEL SECURITY;
ALTER TABLE resenas_estancia ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON perfiles_usuario,calendario_tarifas,facturas,detalles_factura,resenas_estancia FROM anon,authenticated;
COMMIT;

BEGIN;
CREATE TABLE IF NOT EXISTS imagenes_alojamiento (
 id TEXT PRIMARY KEY,
 alojamiento_id INTEGER NOT NULL REFERENCES alojamientos(id),
 orden INTEGER NOT NULL CHECK (orden BETWEEN 1 AND 4),
 url TEXT NOT NULL CHECK (url LIKE 'https://%'),
 descripcion TEXT NOT NULL,
 autor TEXT NOT NULL DEFAULT '',
 licencia TEXT NOT NULL,
 fuente TEXT NOT NULL CHECK (fuente LIKE 'https://%'),
 licencia_url TEXT NOT NULL CHECK (licencia_url LIKE 'https://%'),
 fecha_creacion TEXT NOT NULL,
 UNIQUE(alojamiento_id,orden),
 UNIQUE(alojamiento_id,url)
);
ALTER TABLE imagenes_alojamiento ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON imagenes_alojamiento FROM anon,authenticated;
COMMIT;
