const { chromium, expect } = require('@playwright/test');
const fs = require('node:fs');
const { spawn } = require('node:child_process');
const { randomUUID } = require('node:crypto');
const { setTimeout: delay } = require('node:timers/promises');
const base = 'http://127.0.0.1:3102';
const file = 'data/browser-test-' + randomUUID() + '.sqlite';
let server;
(async () => {
  let browser;
  try {
    server = spawn(process.execPath, ['dist/main.js'], { env: { ...process.env, PORT: '3102', DATABASE_URL: '', DATABASE_SSL: '', VERCEL: '', DATA_FILE: file, ADMIN_EMAIL: 'admin@booking.local', ADMIN_PASSWORD: 'AdminDemo2026!', SEED_DEMO: 'true' }, stdio: 'ignore' });
    for (let i = 0; i < 60; i++) { try { if ((await fetch(base + '/api/v1/health')).ok) break; } catch {} await delay(300); if (i === 59) throw new Error('No se inició el servidor de prueba visual'); }
    browser = await chromium.launch({ channel: 'chrome', headless: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(base + '/admin');
    await expect(page).toHaveURL(base + '/login');
    await expect(page.locator('#login-form')).toBeVisible();
    await page.goto(base);
    await expect(page.locator('.hotel-card')).toHaveCount(6);
    fs.mkdirSync('artifacts', { recursive: true });
    await page.screenshot({ path: 'artifacts/marketplace-desktop.png', fullPage: true });
    await page.getByRole('button', { name: 'Buscar estancia' }).click();
    await expect(page.locator('#result-count')).toContainText('disponibles');
    await page.getByRole('button', { name: 'Ver estancia' }).first().click();
    await page.getByRole('button', { name: 'Consultar disponibilidad' }).click();
    await expect(page.locator('#availability-result')).toContainText('total');
    await page.locator('#close-modal').click();
    await page.getByRole('button', { name: 'Iniciar sesión' }).click();
    await page.locator('input[name=email]').fill('admin@booking.local');
    await page.locator('input[name=password]').fill('AdminDemo2026!');
    await page.locator('#login-form button[type=submit], #login-form .primary').click();
    await expect(page.locator('#admin-nav')).toBeVisible();
    await page.locator('#admin-nav').click();
    await expect(page.getByRole('heading',{name:'Resumen ejecutivo'})).toBeVisible();
    await expect(page.locator('.leaflet-container')).toBeVisible();
    await expect(page.getByText('Eventos de integración',{exact:true})).toHaveCount(0);
    await page.screenshot({path:'artifacts/erp-dashboard-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:'artifacts/erp-dashboard-mobile.png',fullPage:true});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.setViewportSize({width:1440,height:1100});
    await page.locator('[data-tab=gastos]').click();
    await page.getByRole('button',{name:'Registrar gasto'}).click();
    await page.locator('input[name=concepto]').fill('Limpieza visual');
    await page.locator('input[name=proveedor]').fill('Proveedor visual');
    await page.locator('input[name=importe]').fill('75.25');
    await page.locator('select[name=estado]').selectOption('PAGADO');
    await expect(page.locator('select[name=categoria_id] option')).toHaveCount(7);
    await page.locator('#erp-form').getByRole('button',{name:'Guardar',exact:true}).click();
    await expect(page.locator('#admin-content tbody')).toContainText('Limpieza visual');
    await page.locator('[data-tab=dashboard]').click();
    await expect(page.locator('.erp-kpi').nth(1)).toContainText('75,25');
    await page.screenshot({path:'artifacts/erp-dashboard-gastos.png',fullPage:true});
    await page.locator('[data-tab=gastos]').click();
    await page.locator('tbody tr').filter({hasText:'Limpieza visual'}).getByRole('button',{name:'Editar',exact:true}).click();
    await page.locator('input[name=importe]').fill('80.50');
    await page.locator('#erp-form').getByRole('button',{name:'Guardar',exact:true}).click();
    await expect(page.locator('tbody')).toContainText('80,50');
    await page.locator('tbody tr').filter({hasText:'Limpieza visual'}).getByRole('button',{name:'Eliminar',exact:true}).click();
    await page.getByRole('button',{name:'Confirmar eliminación'}).click();
    await expect(page.locator('tbody tr')).toHaveCount(0);
    await page.locator('[data-tab=usuarios]').click();
    await page.getByRole('button',{name:'Crear usuario'}).click();
    await page.locator('input[name=nombre]').fill('Usuario visual');
    await page.locator('input[name=correo]').fill('usuario@visual.local');
    await page.locator('input[name=contrasena]').fill('UsuarioVisual2026!');
    await page.locator('#erp-form').getByRole('button',{name:'Guardar',exact:true}).click();
    const userRow=page.locator('tbody tr').filter({hasText:'usuario@visual.local'});
    await expect(userRow).toContainText('Activo');
    await userRow.getByRole('button',{name:'Desactivar',exact:true}).click();
    await expect(userRow).toContainText('Inactivo');
    await userRow.getByRole('button',{name:'Activar',exact:true}).click();
    await expect(userRow).toContainText('Activo');
    await page.screenshot({path:'artifacts/erp-usuarios.png',fullPage:true});
    await page.locator('[data-tab=ciudades]').click();
    await expect(page.locator('tbody tr')).toHaveCount(6);
    await page.locator('[data-tab=audit]').click();
    await expect(page.locator('tbody')).toContainText('Usuario actualizado');
    await page.locator('[data-tab=properties]').click();
    await expect(page.locator('#admin-content tbody tr')).toHaveCount(6);
    await page.screenshot({ path: 'artifacts/admin-desktop.png', fullPage: true });
    await page.locator('#new-hotel').click();
    await page.locator('input[name=nombre]').fill('Estancia de prueba visual');
    await page.locator('input[name=direccion]').fill('Calle de prueba, Quito');
    await page.locator('textarea[name=descripcion]').fill('Descripción del alojamiento de prueba visual');
    await page.getByRole('button', { name: 'Guardar alojamiento' }).click();
    await expect(page.locator('#admin-content tbody tr')).toHaveCount(7);
    await page.locator('#admin-content tr').filter({ hasText: 'Estancia de prueba visual' }).getByRole('button', { name: 'Editar', exact: true }).click();
    await page.locator('input[name=precioPorNoche]').fill('95.50');
    await page.getByRole('button', { name: 'Guardar alojamiento' }).click();
    await expect(page.locator('#admin-content tr').filter({ hasText: 'Estancia de prueba visual' })).toContainText('95,50');
    await page.locator('#admin-content tr').filter({ hasText: 'Estancia de prueba visual' }).getByRole('button', { name: 'Eliminar', exact: true }).click();
    await page.locator('#confirm-delete').click();
    await expect(page.locator('#admin-content tbody tr')).toHaveCount(6);
    await expect(page.locator('[data-view=orders]')).toHaveCount(0);
    await page.locator('#account').click();
    await page.getByRole('button',{name:'Cerrar sesión'}).click();
    await page.goto(base);
    await page.locator('#account').click();
    await page.locator('#modal-content').getByRole('button',{name:'Registrarme',exact:true}).click();
    await page.locator('input[name=name]').fill('Viajero Prueba');
    await page.locator('input[name=email]').fill('viajero@prueba.local');
    await page.locator('input[name=password]').fill('ViajeroPrueba2026!');
    await page.getByRole('button',{name:'Crear cuenta',exact:true}).click();
    await page.getByRole('button', { name: 'Explorar', exact: true }).click();
    await page.getByRole('button', { name: 'Ver estancia' }).first().click();
    await page.getByRole('button', { name: 'Consultar disponibilidad' }).click();
    await page.getByRole('button', { name: 'Continuar con la reserva' }).click();
    await page.locator('input[name=first_name]').fill('Admin');
    await page.locator('input[name=last_name]').fill('Prueba');
    await page.locator('#checkout-form input[type=checkbox]').check();
    await page.getByRole('button', { name: 'Confirmar reserva' }).click();
    await expect(page.locator('#modal')).toContainText('Reserva confirmada.');
    await page.screenshot({ path: 'artifacts/reserva-confirmada.png' });
    await page.getByRole('button', { name: 'Ver mis reservas' }).click();
    await expect(page.locator('.order-card')).toHaveCount(1);
    await page.getByRole('button', { name: 'Cancelar', exact: true }).click();
    await page.locator('#confirm-cancel').click();
    await expect(page.locator('.order-card')).toContainText('Cancelada');
    await expect(page).toHaveURL(base + '/reservas');
    await page.reload();
    await page.getByRole('button', { name: 'Mis reservas', exact: true }).click();
    await expect(page.locator('.order-card')).toContainText('Cancelada');
    await page.getByRole('button', { name: 'Explorar', exact: true }).click();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: 'artifacts/marketplace-mobile.png', fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    expect(await page.evaluate(() => localStorage.getItem('access_token'))).toBeNull();
    await page.locator('#account').click();
    await page.getByRole('button', { name: 'Cerrar sesión' }).click();
    await page.goto(base + '/admin');
    await expect(page).toHaveURL(base + '/login');
    await expect(page.locator('#admin-view')).toHaveCount(0);
    await page.goto(base+'/api/docs');
    await expect(page.locator('.swagger-ui .info .title')).toContainText('Kawsay');
    const healthOp=page.locator('.opblock').filter({has:page.locator('.opblock-summary-path').filter({hasText:/^\/api\/v1\/health$/})});
    await healthOp.locator('.opblock-summary').click();
    if(!await healthOp.locator('.execute').isVisible())await healthOp.getByRole('button',{name:'Try it out',exact:true}).click();
    const healthResponse=page.waitForResponse(r=>r.url()===base+'/api/v1/health');
    await healthOp.locator('.execute').click();
    expect((await healthResponse).status()).toBe(200);
    await expect(healthOp.locator('.live-responses-table')).toContainText('ok');
    expect(errors).toEqual([]);
    console.log('Interfaz verificada: catálogo, búsqueda, disponibilidad, login, CRUD, reserva, cancelación, persistencia y móvil sin desbordamiento.');
  } finally {
    if (browser) await browser.close();
    if (server && server.exitCode === null) await new Promise(resolve => { server.once('exit', resolve); server.kill(); });
    if (fs.existsSync(file)) fs.unlinkSync(file);
  }
})().catch(e => { console.error(e); process.exitCode = 1; });
