const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const { randomUUID } = require('node:crypto');
const fs = require('node:fs');
const { setTimeout: delay } = require('node:timers/promises');
const port = 3101;
const file = 'data/test-' + randomUUID() + '.sqlite';
const databaseUrl = process.env.TEST_DATABASE_URL || '';
let server;
let logs = '';
function startServer() {
  server = spawn(process.execPath, ['dist/main.js'], { env: { ...process.env, PORT: String(port), DATABASE_URL: databaseUrl, DATABASE_SSL: '', VERCEL: '', DATA_FILE: file, ADMIN_EMAIL: 'admin@booking.local', ADMIN_PASSWORD: 'AdminDemo2026!', SEED_DEMO: 'true' }, stdio: ['ignore', 'pipe', 'pipe'] });
  server.stdout.on('data', c => logs += c); server.stderr.on('data', c => logs += c);
}
async function stopServer() { if (!server || server.exitCode !== null) return; await new Promise(resolve => { server.once('exit', resolve); server.kill(); }); }
async function waitReady() {
  for (let i = 0; i < 60; i++) { try { if ((await api('health')).status === 200) return; } catch {} await delay(300); }
  throw new Error('Servidor no inició: ' + logs);
}
let passed = 0;
function check(condition, name) { assert.ok(condition, name); passed++; console.log('OK ' + name); }
async function api(path, body, token, method = body === undefined ? 'GET' : 'POST', extra = {}) {
  const r = await fetch(`http://127.0.0.1:${port}/api/v1/` + path, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}), ...extra }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  return { status: r.status, headers: r.headers, body: r.status === 204 ? null : await r.json() };
}
(async () => {
  if (databaseUrl) {
    // This initializer is restricted to an ephemeral CI database, never Supabase.
    const url = new URL(databaseUrl);
    if (process.env.CI !== 'true' || url.pathname !== '/booking_test' || !['localhost', '127.0.0.1'].includes(url.hostname)) throw new Error('TEST_DATABASE_URL solo admite booking_test local en CI');
    const { Client } = require('pg'); const pg = new Client({ connectionString: databaseUrl }); await pg.connect();
    try { await pg.query('CREATE ROLE anon; CREATE ROLE authenticated;'); await pg.query(fs.readFileSync('supabase/migrations/001_booking.sql', 'utf8')); await pg.query(fs.readFileSync('supabase/migrations/002_nombres_espanol.sql', 'utf8')); await pg.query(fs.readFileSync('supabase/migrations/003_erp.sql', 'utf8')); await pg.query(fs.readFileSync('supabase/migrations/004_estancias.sql', 'utf8')); await pg.query(fs.readFileSync('supabase/migrations/005_galerias.sql','utf8')); }
    finally { await pg.end(); }
  }
  startServer(); await waitReady();
  check((await api('health')).body.status === 'ok', 'Base SQL operativa');
  const yamlSource = await (await fetch('http://127.0.0.1:' + port + '/api/contrato.yaml')).text();
  check(yamlSource === fs.readFileSync('contracts/kawsay-estancias-openapi.yaml', 'utf8'), 'Publica exactamente el contrato propio del repositorio');
  const ownContract = require('yaml').parse(yamlSource);
  const Ajv = require('ajv'); const addFormats = require('ajv-formats');
  const responseAjv = new Ajv({ strict: false, allErrors: true }); addFormats(responseAjv);
  responseAjv.addSchema({ $id: 'own-contract', components: ownContract.components });
  function conforms(name, body) { const validate = responseAjv.compile({ $ref: 'own-contract#/components/schemas/' + name }); check(validate(body), 'Respuesta real cumple contrato propio: ' + name + (validate.errors ? JSON.stringify(validate.errors) : '')); }
  const guestSession = await api('auth/session');
  check(guestSession.status === 200 && guestSession.body.user === null, 'Visitante consulta sesión sin generar HTTP 401');
  conforms('SessionResponse', guestSession.body);
  check((await api('auth/session', undefined, 'token-invalido')).body.user === null, 'Sesión inválida se representa como visitante');
  const favicon = await fetch('http://127.0.0.1:' + port + '/favicon.ico');
  check(favicon.status === 200 && favicon.headers.get('content-type').includes('image/svg+xml'), 'Icono de pestaña disponible sin HTTP 404');
  const catalog = (await api('catalog')).body.data;
  check(catalog.length === 6, 'Catálogo inicial de seis alojamientos');
  check((await api('admin/accommodations')).status === 401, 'Administración exige autenticación');
  const admin = (await api('auth/login', { email: 'admin@booking.local', password: 'AdminDemo2026!' })).body.access_token;
  check(!!admin, 'Inicio de sesión administrador');
  const registration={name:'María José',email:'validacion@test.local',password:'ClienteDemo2026!'};
  for(const [field,value] of [['name','Juan123'],['name','  '],['name','A'],['name','A'.repeat(101)],['email','uno@@test.local'],['email','a'.repeat(255)+'@test.local'],['password','corta'],['password','x'.repeat(129)]])check((await api('auth/register',{...registration,[field]:value})).status===400,'Registro rechaza '+field+' inválido: '+String(value).length+' caracteres');
  const invalidUser={nombre:'Juan123',correo:'validacionadmin@test.local',rol:'customer',activo:true,contrasena:'ClienteDemo2026!'};
  check((await api('admin/erp/usuarios',invalidUser,admin)).status===400,'Administrador no crea nombres con números');
  check((await api('admin/erp/usuarios',{...invalidUser,nombre:'María José',correo:'uno@@test.local'},admin)).status===400,'Administrador rechaza doble arroba');
  check((await api('admin/erp/usuarios',{...invalidUser,nombre:'María José',contrasena:'x'.repeat(129)},admin)).status===400,'Administrador rechaza contraseña de más de 128 caracteres');
  check(admin.split('.').length === 3 && JSON.parse(Buffer.from(admin.split('.')[1], 'base64url')).iss === 'booking-prototipo', 'Autenticación emite JWT con emisor');
  const tampered = admin.split('.'); const claims = JSON.parse(Buffer.from(tampered[1], 'base64url')); claims.sub = 'otro-usuario'; tampered[1] = Buffer.from(JSON.stringify(claims)).toString('base64url');
  check((await api('auth/me', undefined, tampered.join('.'))).status === 401, 'JWT alterado rechazado por la API');
  const cors = await api('health', undefined, null, 'GET', { Origin: 'http://localhost:5173' });
  check(cors.headers.get('access-control-allow-origin') === 'http://localhost:5173' && cors.headers.get('access-control-allow-credentials') === 'true', 'CORS permite el frontend autorizado con credenciales');
  const evilCors = await api('health', undefined, null, 'GET', { Origin: 'https://atacante.test' });
  check(!evilCors.headers.get('access-control-allow-origin'), 'CORS no concede lectura a un origen extraño');
  check((await api('auth/login', { email: 'admin@booking.local', password: 'AdminDemo2026!' }, null, 'POST', { Origin: 'https://atacante.test' })).status === 403, 'Origen extraño no puede ejecutar escrituras');
  const revocable = (await api('auth/login', { email: 'admin@booking.local', password: 'AdminDemo2026!' })).body.access_token;
  await api('auth/logout', {}, revocable);
  check((await api('auth/me', undefined, revocable)).status === 401, 'Logout revoca un JWT aún no vencido');
  const a = (await api('auth/register', { name: 'Cliente Uno', email: 'uno@test.local', password: 'ClienteDemo2026!' })).body.access_token;
  const b = (await api('auth/register', { name: 'Cliente Dos', email: 'dos@test.local', password: 'ClienteDemo2026!' })).body.access_token;
  const authenticatedSession = (await api('auth/session', undefined, a)).body;
  check(authenticatedSession.user.role === 'customer', 'Consulta de sesión conserva la identidad del viajero');
  conforms('SessionResponse', authenticatedSession);
  check((await api('admin/accommodations', undefined, a)).status === 403, 'Cliente no puede administrar');
  check((await api('auth/register', { name: 'Hack', email: 'hack@test.local', password: 'ClienteDemo2026!', role: 'admin' })).body.user.role === 'customer', 'Registro no permite escalar privilegios');
  const start = new Date(); start.setUTCDate(start.getUTCDate() + 30); const end = new Date(start); end.setUTCDate(end.getUTCDate() + 2);
  const input = { booker: { country: 'ec', platform: 'desktop' }, checkin: start.toISOString().slice(0, 10), checkout: end.toISOString().slice(0, 10), guests: { number_of_adults: 2, number_of_rooms: 1, children: [] }, currency: 'USD' };
  check((await api('search', input)).status === 400, 'Búsqueda exige fingerprint');
  check((await api('search', { ...input, checkout: input.checkin }, null, 'POST', { 'X-Device-Fingerprint': 'test' })).status === 400, 'Rechaza fechas invertidas');
  check((await api('search', { ...input, guests: { number_of_adults: 0, number_of_rooms: 1 } }, null, 'POST', { 'X-Device-Fingerprint': 'test' })).status === 400, 'Valida contrato de huéspedes');
  check((await api('search', input, null, 'POST', { 'X-Device-Fingerprint': 'test' })).body.data.length === 6, 'Búsqueda devuelve disponibilidad');
  check((await api('search', { ...input, currency: 'EUR' }, null, 'POST', { 'X-Device-Fingerprint': 'test' })).status === 400, 'No inventa conversión de moneda');
  const h = { nombre: 'Prueba transaccional', cityId: 1, descripcion: 'Alojamiento para pruebas', direccion: 'Calle de prueba', tipo: 'Hotel de prueba', image: catalog[0].image, published: true, precioPorNoche: 25.55, capacidadAdultos: 2, capacidadNinos: 1, habitaciones: 1, tienePiscina: false };
  const created = await api('admin/accommodations', h, admin);
  check(created.status === 201, 'CRUD crear alojamiento');
  const hid = created.body.id;
  check(created.headers.get('location') === '/api/v1/admin/accommodations/' + hid, 'POST devuelve Location del recurso creado');
  check((await api('admin/accommodations/' + hid, undefined, admin)).body._links.update.method === 'PATCH', 'GET por ID y enlaces HATEOAS administrativos');
  check((await api('catalog/' + hid)).body.data.id === hid, 'Detalle público por ID');
  check((await api('admin/accommodations/abc', undefined, admin)).status === 400, 'ID no numérico devuelve 400');
  check((await api('admin/accommodations/0', undefined, admin)).status === 400, 'ID cero no permite crear accidentalmente con PATCH');
  check((await api('admin/accommodations/999999', undefined, admin)).status === 404, 'GET de ID inexistente devuelve 404');
  check((await api('admin/accommodations', { ...h, precioPorNoche: '25.55' }, admin)).status === 400, 'DTO rechaza precio como cadena');
  check((await api('admin/accommodations', { ...h, precioPorNoche: 25.555 }, admin)).status === 400, 'DTO exige importes con máximo dos decimales');
  check((await api('admin/accommodations/' + hid, { cityId: null }, admin, 'PATCH')).status === 400, 'PATCH rechaza null en campos requeridos');
  check((await api('admin/accommodations/' + hid, { unexpected: 'dato' }, admin, 'PATCH')).status === 400, 'DTO rechaza campos no definidos');
  check((await api('admin/accommodations/' + hid, { nombre: 'Solo nombre' }, admin, 'PUT')).status === 400, 'PUT requiere representación completa');
  const replaced = await api('admin/accommodations/' + hid, { ...h, nombre: 'Prueba reemplazada' }, admin, 'PUT');
  check(replaced.status === 204 && replaced.body === null, 'PUT reemplaza y responde 204 sin cuerpo');
  check((await api('admin/accommodations/' + hid, undefined, admin)).body.nombre === 'Prueba reemplazada', 'GET refleja datos reemplazados por PUT');
  check((await api('admin/accommodations?nombre=REEMPLAZADA', undefined, admin)).body.data.length === 1, 'Filtro por nombre insensible a mayúsculas');
  check((await api('catalog?nombre=nombre-inexistente')).body.data.length === 0, 'Lista sin coincidencias responde 200 con arreglo vacío');
  check((await api('admin/accommodations/' + hid, { precioPorNoche: 26.55 }, admin, 'PATCH')).status === 200, 'CRUD editar tarifa');
  const av = (await api('availability', { ...input, accommodation: hid })).body.data;
  conforms('Availability', av);
  check(av.available && av.products[0].total_price === 53.1, 'Precio calculado en servidor con centavos');
  const previewInput = { accommodation_id: hid, product_id: av.products[0].id, guests: input.guests };
  check((await api('orders/preview',previewInput,admin)).status===403,'Admin no puede cotizar reservas personales');
  const qa = (await api('orders/preview', previewInput, a)).body.data;
  conforms('Quote', qa);
  const qb = (await api('orders/preview', previewInput, b)).body.data;
  const order = q => ({ order_preview_id: q.order_preview_id, payment_reference: 'DEMO-TEST', customer_details: { first_name: 'Cliente', last_name: 'Prueba', email: 'uno@test.local' } });
  check((await api('orders/create',order(qa),admin,'POST',{'Idempotency-Key':randomUUID()})).status===403,'Admin no puede crear reservas personales');
  const keyA = randomUUID(); const keyB = randomUUID();
  check((await api('orders/create', order(qa), a)).status === 400, 'Reserva exige idempotencia');
  const results = await Promise.all([api('orders/create', order(qa), a, 'POST', { 'Idempotency-Key': keyA }), api('orders/create', order(qb), b, 'POST', { 'Idempotency-Key': keyB })]);
  check(results.filter(r => r.status === 201).length === 1 && results.filter(r => r.status === 409).length === 1, 'Dos reservas concurrentes no sobrevendan una habitación');
  const winner = results[0].status === 201 ? { r: results[0], token: a, other: b, q: qa, key: keyA } : { r: results[1], token: b, other: a, q: qb, key: keyB };
  const oid = winner.r.body.order_id;
  conforms('Reservation', winner.r.body);
  const replay = await api('orders/create', order(winner.q), winner.token, 'POST', { 'Idempotency-Key': winner.key });
  check(replay.body.order_id === oid, 'Reintento idempotente devuelve la misma reserva');
  check((await api('orders/create', { ...order(winner.q), payment_reference: 'DEMO-DIFFERENT' }, winner.token, 'POST', { 'Idempotency-Key': winner.key })).status === 409, 'Detecta reutilización de clave con distinto contenido');
  check((await api('orders/' + oid, undefined, winner.other)).status === 404, 'No expone reservas ajenas');
  check(!(await api('availability', { ...input, accommodation: hid })).body.data.available, 'Inventario ocupado después de confirmar');
  check((await api('orders/' + oid + '/modify', { checkin: input.checkin, checkout: input.checkout }, winner.token, 'POST', { 'Idempotency-Key': randomUUID() })).status === 200, 'Modificación excluye la propia reserva del inventario');
  check((await api('admin/accommodations/' + hid, { capacidadAdultos: 1 }, admin, 'PATCH')).status === 409, 'No reduce capacidad afectando reservas');
  const cancelKey = randomUUID();
  check((await api('orders/' + oid + '/cancel', {}, winner.token, 'POST', { 'Idempotency-Key': cancelKey })).body.status === 'CANCELLED', 'Cancelación persistida');
  check((await api('orders/' + oid + '/cancel', {}, winner.token, 'POST', { 'Idempotency-Key': cancelKey })).body.status === 'CANCELLED', 'Cancelación idempotente');
  check((await api('availability', { ...input, accommodation: hid })).body.data.available, 'Cancelación libera inventario');
  check((await api('admin/accommodations/' + hid, undefined, admin, 'DELETE')).status === 409, 'Historial impide borrado destructivo');
  await api('admin/accommodations/' + hid, { published: false }, admin, 'PATCH');
  check(!(await api('catalog')).body.data.some(h => h.id === hid), 'Despublicación retira propiedad del marketplace');
  check((await api('catalog/' + hid)).status === 404, 'Detalle público oculta propiedad despublicada');
  const removable = (await api('admin/accommodations', { ...h, nombre: 'Para eliminar' }, admin)).body;
  check((await api('admin/accommodations/' + removable.id, undefined, admin, 'DELETE')).status === 204, 'CRUD elimina alojamiento sin historial');
  check((await api('admin/accommodations/' + removable.id, undefined, admin, 'DELETE')).status === 404, 'Segundo DELETE devuelve 404');
  check((await api('admin/accommodations/' + removable.id, h, admin, 'PUT')).status === 404, 'PUT de ID eliminado no crea otra propiedad');
  check((await api('admin/events', undefined, admin)).body.data.some(e => e.eventType === 'ORDER_CONFIRMED'), 'Outbox registra eventos confirmados');
  const webhookId = randomUUID();
  check((await api('webhooks', { id: webhookId, url: 'https://example.com/events', events: ['ORDER_CONFIRMED'], secret: 'secret-demostracion-123' }, admin)).status === 201, 'Contrato de suscripción webhook');
  check(!(await api('webhooks', undefined, admin)).body[0].secret, 'No expone secreto de webhook');
  check((await api('webhooks/' + webhookId, undefined, admin, 'DELETE')).status === 204, 'Elimina suscripción webhook');
  const doc = await (await fetch(`http://127.0.0.1:${port}/api/openapi.json`)).json();
  check(doc.paths['/api/v1/orders/create'].post.requestBody && doc.components.schemas.OrderCreateRequest, 'Swagger incluye esquemas del contrato');
  check(doc.paths['/api/v1/admin/accommodations/{id}'].put.responses['204'], 'Swagger documenta PUT y su código 204');
  check((await api('details', { accommodations: [1] })).body.data.length === 1, 'Detalles del catálogo');
  check((await api('reviews/scores', { accommodations: [1] })).body.data[0].count === 1, 'Reseñas y puntuaciones persistidas');
  check((await api('constants', {})).body.data.cities.length === 6, 'Constantes y destinos');
  await stopServer(); startServer(); await waitReady();
  check((await api('orders/' + oid, undefined, winner.token)).body.status === 'CANCELLED', 'Reserva y sesión persisten tras reinicio del servidor');
  check((await api('admin/accommodations/' + hid, undefined, admin)).body.published === false, 'Cambios administrativos persisten tras reinicio');

  const own=(await api('auth/me',undefined,admin)).body;
  check((await api('orders',undefined,admin)).status===403,'Administrador no tiene Mis reservas');
  check((await api('admin/erp/dashboard',undefined,a)).status===403,'Dashboard protegido por rol');
  const dashboard=(await api('admin/erp/dashboard',undefined,admin)).body;
  check(dashboard.indicadores.ciudades===6,'Dashboard usa destinos persistidos');
  const adminBody = {nombre:'Administrador adicional',correo:'admin-adicional@test.local',rol:'admin',activo:true,contrasena:'AdminAdicional2026!'};
  check((await api('admin/erp/usuarios',adminBody)).status===401,'Crear administrador exige sesión');
  check((await api('admin/erp/usuarios',adminBody,a)).status===403,'Un viajero no puede crear administradores');
  for (const rol of ['customer', 'admin']) {
    const inactiveBody = {...adminBody,correo:'inactivo-'+rol+'@test.local',rol,activo:false};
    check((await api('admin/erp/usuarios',inactiveBody,admin)).status===400,'No permite crear cuenta inactiva: '+rol);
    check(!(await api('admin/erp/usuarios',undefined,admin)).body.some(u=>u.correo===inactiveBody.correo),'La cuenta inactiva rechazada no se guarda: '+rol);
  }
  const additionalAdmin=(await api('admin/erp/usuarios',adminBody,admin)).body;
  check(!!additionalAdmin.id&&additionalAdmin.rol==='admin'&&!additionalAdmin.hash_contrasena,'Administrador crea otro administrador sin exponer credenciales');
  conforms('AdminUserView', additionalAdmin);
  const additionalToken=(await api('auth/login',{email:adminBody.correo,password:adminBody.contrasena})).body.access_token;
  check((await api('admin/erp/usuarios',undefined,additionalToken)).status===200,'Nuevo administrador accede a gestión de usuarios');
  const delegatedAdmin=(await api('admin/erp/usuarios',{...adminBody,nombre:'Administrador delegado',correo:'admin-delegado@test.local'},additionalToken)).body;
  check(delegatedAdmin.rol==='admin','Nuevo administrador puede crear más administradores');
  check((await api('admin/erp/usuarios/'+additionalAdmin.id,{rol:'admin'},a,'PATCH')).status===403,'Un viajero no puede asignar el rol administrador');
  await api('admin/erp/usuarios/'+delegatedAdmin.id,{activo:false},admin,'PATCH');
  await api('admin/erp/usuarios/'+additionalAdmin.id,{activo:false},admin,'PATCH');
  check((await api('auth/me',undefined,additionalToken)).status===401,'Desactivar administrador nuevo revoca su sesión');
  const user=(await api('admin/erp/usuarios',{nombre:'Prueba ERP',correo:'erp@test.local',rol:'customer',activo:true,contrasena:'PasswordERP2026!'},admin)).body;
  check(!!user.id&&!user.passwordHash&&!user.hash_contrasena,'Usuario creado sin exponer hash');
  check((await api('admin/erp/usuarios',{nombre:'Duplicado',correo:'ERP@test.local',rol:'customer',activo:true,contrasena:'PasswordERP2026!'},admin)).status===409,'Correo normalizado y duplicados rechazados');
  const userToken=(await api('auth/login',{email:user.correo,password:'PasswordERP2026!'})).body.access_token;
  check((await api('admin/erp/usuarios/'+user.id,{activo:false},admin,'PATCH')).status===200,'Usuario desactivado');
  check((await api('auth/me',undefined,userToken)).status===401,'Desactivación revoca sesión');
  check((await api('auth/login',{email:user.correo,password:'PasswordERP2026!'})).status===403,'Usuario inactivo no ingresa');
  check((await api('admin/erp/usuarios/'+own.id,{activo:false},admin,'PATCH')).status===409,'Admin no puede desactivar su cuenta');
  check((await api('admin/erp/usuarios/'+own.id,{rol:'customer'},admin,'PATCH')).status===409,'Admin no puede quitarse su rol');
  await api('admin/erp/usuarios/'+user.id,{activo:true},admin,'PATCH');
  const beforeReset=(await api('auth/login',{email:user.correo,password:'PasswordERP2026!'})).body.access_token;
  await api('admin/erp/usuarios/'+user.id,{contrasena:'NuevaPassword2026!'},admin,'PATCH');
  check((await api('auth/me',undefined,beforeReset)).status===401,'Cambio de contraseña revoca sesiones');
  check((await api('auth/login',{email:user.correo,password:'NuevaPassword2026!'})).status===201,'Nueva contraseña operativa');
  const category=(await api('admin/erp/categorias',{nombre:'Categoría prueba'},admin)).body;
  check(!!category.id,'CRUD categoría creada');
  check((await api('admin/erp/categorias/'+category.id,{nombre:'Categoría editada'},admin,'PATCH')).status===200,'CRUD categoría editada');
  const expenseBody={concepto:'Limpieza prueba',proveedor:'Proveedor prueba',categoria_id:category.id,alojamiento_id:1,importe:125.55,fecha:new Date().toISOString().slice(0,10),estado:'PAGADO',notas:'Prueba'};
  const expense=(await api('admin/erp/gastos',expenseBody,admin)).body;
  check(!!expense.id,'CRUD gasto creado');
  check((await api('admin/erp/dashboard',undefined,admin)).body.indicadores.gastos_pagados===125.55,'Dashboard suma gasto pagado con centavos');
  check((await api('admin/erp/categorias/'+category.id,undefined,admin,'DELETE')).status===409,'Categoría con gastos no se elimina');
  check((await api('admin/erp/gastos',{...expenseBody,fecha:'2026-02-30'},admin)).status===400,'Gasto con fecha inexistente rechazado');
  check((await api('admin/erp/gastos',{...expenseBody,importe:-1},admin)).status===400,'Importe negativo rechazado');
  check((await api('admin/erp/gastos',{...expenseBody,categoria_id:9999},admin)).status===400,'Categoría inexistente rechazada');
  await api('admin/erp/gastos/'+expense.id,{importe:50.25,estado:'PENDIENTE',alojamiento_id:null},admin,'PATCH');
  const afterExpense=(await api('admin/erp/dashboard',undefined,admin)).body;
  check(afterExpense.indicadores.gastos_pagados===0&&afterExpense.indicadores.gastos_pendientes===50.25,'Gastos pendientes separados de pagados');
  check((await api('admin/erp/gastos',undefined,admin)).body[0].alojamiento==='Operación general','Gasto admite operación general');
  check((await api('admin/erp/gastos/'+expense.id,undefined,admin,'DELETE')).status===204,'CRUD gasto eliminado');
  check((await api('admin/erp/categorias/'+category.id,undefined,admin,'DELETE')).status===204,'CRUD categoría eliminada');
  const cityBody={nombre:'Destino prueba',codigo:'9999',provincia:'Provincia prueba',region:'Sierra',latitud:-1,longitud:-78};
  const city=(await api('admin/erp/ciudades',cityBody,admin)).body;
  check(!!city.id,'CRUD destino creado');
  check((await api('admin/erp/ciudades',cityBody,admin)).status===409,'Código cantonal único');
  check((await api('admin/erp/ciudades/'+city.id,{nombre:'Destino editado'},admin,'PATCH')).status===200,'CRUD destino editado');
  check((await api('admin/erp/ciudades/1',undefined,admin,'DELETE')).status===409,'Destino con alojamientos conserva historial');
  check((await api('admin/erp/ciudades/'+city.id,undefined,admin,'DELETE')).status===204,'CRUD destino eliminado');
  check((await api('admin/erp/dashboard?desde=2026-02-30',undefined,admin)).status===400,'Dashboard valida período calendario');
  const newDoc=await(await fetch('http://127.0.0.1:'+port+'/api/docs-json')).json();
  check(newDoc.components.schemas.GastoDto.properties.importe.type==='number','Swagger documenta campos de gastos');
  check((await api('me/profile',{nombre:'Cliente actualizado',telefono:'+593999123456',documento:'DEMO123',direccion:'Quito'},a,'PATCH')).status===200,'Perfil editable propio');
  check((await api('me/profile',undefined,b)).body.nombre==='Cliente Dos','Perfil no expone datos ajenos');
  const calendar={alojamiento_id:1,desde:input.checkin,hasta:input.checkin,precio:40.15,cupo:1,cerrado:false,nota:'Temporada prueba'};
  check((await api('admin/erp/tarifas',calendar,a)).status===403,'Calendario protegido por rol');
  check((await api('admin/erp/tarifas',{...calendar,desde:'2026-02-30'},admin)).status===400,'Calendario rechaza fechas inexistentes');
  check((await api('admin/erp/tarifas',calendar,admin)).body.dias===1,'Tarifa por día guardada');
  const priced=(await api('availability',{...input,accommodation:1})).body.data;
  check(priced.available&&priced.products[0].desglose[0].precio_unitario===40.15,'Disponibilidad aplica tarifa especial por noche');
  const quote=(await api('orders/preview',{accommodation_id:1,product_id:priced.products[0].id,guests:input.guests},a)).body.data;
  const staleQuote=(await api('orders/preview',{accommodation_id:1,product_id:priced.products[0].id,guests:input.guests},a)).body.data;
  const otherQuote=(await api('orders/preview',{accommodation_id:1,product_id:priced.products[0].id,guests:input.guests},b)).body.data;
  const fresh=(await api('orders/create',order(quote),a,'POST',{'Idempotency-Key':randomUUID()})).body;
  check(!!fresh.order_id,'Reserva con calendario confirmada');
  check((await api('orders/create',order(staleQuote),a,'POST',{'Idempotency-Key':randomUUID()})).status===409,'Una cotización anterior no permite duplicar fechas propias');
  await api('admin/erp/tarifas',{...calendar,cupo:3},admin);
  const ownAvailability=(await api('availability',{...input,accommodation:1},a)).body.data;
  check(!ownAvailability.available&&ownAvailability.motivo.includes('Ya tienes una reserva'),'Disponibilidad se actualiza y bloquea reserva propia coincidente');
  const otherAvailability=(await api('availability',{...input,accommodation:1},b)).body.data;
  check(!otherAvailability.available&&otherAvailability.available_rooms===0&&otherAvailability.products.length===0,'Reserva bloquea las fechas para otro viajero aunque exista cupo adicional');
  check(!(await api('availability',{...input,accommodation:1})).body.data.available,'Reserva bloquea disponibilidad sin iniciar sesión');
  check((await api('orders/create',order(otherQuote),b,'POST',{'Idempotency-Key':randomUUID()})).status===409,'Cotización previa de otro viajero no permite reservar fechas ocupadas');
  check((await api('orders/preview',{accommodation_id:1,product_id:priced.products[0].id,guests:input.guests},b)).status===409,'No cotiza un producto anterior con fechas ya ocupadas');
  const partial={...input,checkin:new Date(Date.parse(input.checkin)+86400000).toISOString().slice(0,10)};
  check(!(await api('availability',{...partial,accommodation:1},a)).body.data.available,'También bloquea solapamiento parcial de fechas propias');
  check(!(await api('availability',{...partial,accommodation:1},b)).body.data.available,'Solapamiento parcial queda bloqueado para otro viajero');
  const adjacent={...input,checkin:input.checkout,checkout:new Date(Date.parse(input.checkout)+86400000).toISOString().slice(0,10)};
  check((await api('availability',{...adjacent,accommodation:1},b)).body.data.available,'La noche de salida queda libre para una estancia siguiente');
  check(!(await api('search',input,b,'POST',{'X-Device-Fingerprint':'test'})).body.data.some(h=>h.id===1),'Búsqueda de otro viajero excluye el alojamiento reservado');
  check(!(await api('search',input,a,'POST',{'X-Device-Fingerprint':'test'})).body.data.some(h=>h.id===1),'Búsqueda actualizada excluye la estancia ya reservada por el viajero');
  const invoice=(await api('orders/'+fresh.order_id+'/invoice',undefined,a)).body;
  check(invoice.total===priced.products[0].total_price&&invoice.detalles.length===2&&invoice.cliente.documento==='DEMO123','Factura conserva total, noches e identidad del perfil');
  check((await api('orders/'+fresh.order_id+'/invoice',undefined,b)).status===404,'Factura ajena no es accesible');
  check((await api('admin/erp/tarifas',{...calendar,cerrado:true},admin)).status===409,'Calendario no cierra cupo ya reservado');
  check((await api('orders/'+fresh.order_id+'/review',{puntuacion:10,comentario:'Excelente estancia de prueba'},a)).status===409,'Reseña exige estancia finalizada');
  check((await api('orders/'+fresh.order_id+'/review',{puntuacion:11,comentario:'Excelente estancia de prueba'},a)).status===400,'Puntuación fuera de escala rechazada');
  check((await api('orders/'+fresh.order_id+'/modify',{checkin:input.checkin,checkout:input.checkout},a,'POST',{'Idempotency-Key':randomUUID()})).status===200,'Modificación actualiza factura en la transacción');
  check((await api('orders/'+fresh.order_id+'/invoice',undefined,a)).body.version===2,'Factura conserva número y aumenta versión');
  check((await api('orders/'+oid+'/review',{puntuacion:10,comentario:'Estancia cancelada de prueba'},winner.token)).status===409,'Reserva cancelada no admite reseña');
  check((await api('orders/'+fresh.order_id+'/review',{puntuacion:10,comentario:'Comentario administrativo'},admin)).status===403,'Administrador no reseña estancias');
  // Fixture de estancia finalizada, exclusivamente en la base aislada de prueba.
  await stopServer();
  const {Database}=require('../dist/modules/alojamientos/database');
  const oldEnv={DATABASE_URL:process.env.DATABASE_URL,DATABASE_SSL:process.env.DATABASE_SSL,DATA_FILE:process.env.DATA_FILE};
  process.env.DATABASE_URL=databaseUrl;process.env.DATABASE_SSL='';process.env.DATA_FILE=file;
  const fixture=new Database();
  try {await fixture.ready();const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);const previous=new Date(Date.now()-2*86400000).toISOString().slice(0,10);await fixture.transaction(em=>em.update('orders',{id:fresh.order_id},{checkin:previous,checkout:yesterday}));}
  finally {await fixture.onModuleDestroy();for(const [key,value] of Object.entries(oldEnv)){if(value===undefined)delete process.env[key];else process.env[key]=value;}}
  startServer();await waitReady();
  const reviewed=await api('orders/'+fresh.order_id+'/review',{puntuacion:9,comentario:'Una estancia finalizada excelente'},a);
  check(reviewed.status===201,'Viajero reseña estancia propia completada');
  check((await api('orders/'+fresh.order_id+'/review',{puntuacion:9,comentario:'Intento duplicado de estancia'},a)).status===409,'Una reseña por reserva');
  check((await api('admin/erp/resenas/'+reviewed.body.id,{respuesta:'Gracias por visitarnos'},admin,'PATCH')).status===200,'Administrador responde reseña');
  const publicReview=(await api('catalog/1')).body.data.reviews.find(r=>r.id===reviewed.body.id);
  check(publicReview.reply==='Gracias por visitarnos'&&!publicReview.email&&!publicReview.documento&&!publicReview.usuario_id,'Reseña pública y respuesta sin datos privados');
  check((await api('me/reviews',undefined,a)).body.length===1,'Viajero consulta sus reseñas');
  check((await api('admin/erp/facturas',undefined,admin)).body.some(f=>f.reserva_id===fresh.order_id),'ERP lista facturas emitidas');
  check((await api('orders/'+oid+'/invoice',undefined,winner.token)).body.estado==='ANULADA','Cancelación anula factura simulada');
  const calendarRows=(await api('admin/erp/tarifas',undefined,admin)).body;
  check((await api('admin/erp/tarifas/'+calendarRows[0].id,undefined,admin,'DELETE')).status===204,'Calendario permite restaurar tarifa base');
  const publicGallery=(await api('catalog/1/gallery')).body;
  check(publicGallery.length===4&&new Set(publicGallery.map(i=>i.url)).size===4,'Alojamiento ofrece cuatro imágenes distintas y ordenadas');
  check(publicGallery.every((i,index)=>i.orden===index+1&&i.licencia&&i.fuente.startsWith('https://')),'Galería conserva orden y atribución');
  check((await api('catalog/'+hid+'/gallery')).status===404,'Galería de alojamiento despublicado no se expone');
  const photoHotel=(await api('admin/accommodations',{...h,nombre:'Galería editable prueba'},admin)).body;
  const galleryEdit={imagenes:[0,1,2,3].map(i=>({url:'https://example.com/galeria-'+i+'.jpg',descripcion:'Imagen de prueba '+i,autor:'Autor prueba',licencia:'CC BY 4.0',fuente:'https://example.com/fuente',licencia_url:'https://creativecommons.org/licenses/by/4.0/'}))};
  check(photoHotel.galeria.length===4,'Alta administrativa crea una galería de cuatro imágenes');
  check((await api('admin/accommodations/'+photoHotel.id+'/gallery',galleryEdit,a,'PUT')).status===403,'Viajero no puede editar la galería');
  check((await api('admin/accommodations/'+photoHotel.id+'/gallery',{imagenes:galleryEdit.imagenes.slice(0,3)},admin,'PUT')).status===400,'Galería exige exactamente cuatro imágenes');
  check((await api('admin/accommodations/'+photoHotel.id+'/gallery',{imagenes:[galleryEdit.imagenes[0],...galleryEdit.imagenes.slice(0,3)]},admin,'PUT')).status===400,'Galería rechaza imágenes repetidas');
  check((await api('admin/accommodations/'+photoHotel.id+'/gallery',{imagenes:galleryEdit.imagenes.map((img,i)=>i===0?{...img,url:'javascript:alert(1)'}:img)},admin,'PUT')).status===400,'Galería rechaza URL insegura');
  check((await api('admin/accommodations/'+photoHotel.id+'/gallery',galleryEdit,admin,'PUT')).status===200,'Administrador reemplaza galería con créditos');
  check((await api('catalog/'+photoHotel.id)).body.data.image===galleryEdit.imagenes[0].url,'Primera imagen se sincroniza con la portada');
  await api('admin/accommodations/'+photoHotel.id,{nombre:'Galería renombrada'},admin,'PATCH');
  check((await api('catalog/'+photoHotel.id+'/gallery')).body[1].autor==='Autor prueba','Editar alojamiento conserva galería y créditos');
  check((await api('admin/accommodations/'+photoHotel.id,{image:galleryEdit.imagenes[2].url},admin,'PATCH')).status===200,'Portada existente reordena galería sin duplicar URLs');
  check((await api('catalog/'+photoHotel.id+'/gallery')).body[0].url===galleryEdit.imagenes[2].url,'Cambio de portada se refleja inmediatamente en galería');
  check((await api('admin/accommodations/'+photoHotel.id,undefined,admin,'DELETE')).status===204,'Baja sin historial elimina galería sin romper claves foráneas');
  check((await api('admin/accommodations/'+photoHotel.id+'/gallery',undefined,admin)).status===404,'Galería eliminada ya no está accesible');
  console.log('\n'+passed+' comprobaciones superadas.');

})().catch(e => { console.error(e); console.error(logs.slice(-2500)); process.exitCode = 1; }).finally(async () => { await stopServer(); if (fs.existsSync(file)) fs.unlinkSync(file); });
