-- Booking Prototipo · RDA 1
-- Ejecutar una sola vez en un proyecto nuevo de Supabase.
BEGIN;
CREATE TABLE IF NOT EXISTS "users" (
  "id" TEXT PRIMARY KEY,
  "email" TEXT NOT NULL UNIQUE,
  "name" TEXT NOT NULL,
  "passwordHash" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "createdAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "sessions" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "expiresAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "cities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "country" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "chains" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "accommodations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" TEXT NOT NULL,
  "cityId" INTEGER NOT NULL,
  "destino" TEXT NOT NULL,
  "descripcion" TEXT NOT NULL,
  "direccion" TEXT NOT NULL,
  "tipo" TEXT NOT NULL,
  "image" TEXT NOT NULL,
  "published" BOOLEAN NOT NULL,
  "createdAt" TEXT NOT NULL,
  "updatedAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "room_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "accommodationId" INTEGER NOT NULL,
  "nombre" TEXT NOT NULL,
  "capacidadAdultos" INTEGER NOT NULL,
  "capacidadNinos" INTEGER NOT NULL,
  "habitaciones" INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "rate_plans" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "roomTypeId" INTEGER NOT NULL,
  "precioPorNoche" NUMERIC(10,2) NOT NULL,
  "currency" TEXT NOT NULL,
  "cancellation" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "facilities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "accommodation_facilities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "accommodationId" INTEGER NOT NULL,
  "facilityId" INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "photos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "accommodationId" INTEGER NOT NULL,
  "url" TEXT NOT NULL,
  "caption" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "accommodationId" INTEGER NOT NULL,
  "author" TEXT NOT NULL,
  "score" INTEGER NOT NULL,
  "comment" TEXT NOT NULL,
  "createdAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "availability_products" (
  "id" TEXT PRIMARY KEY,
  "accommodationId" INTEGER NOT NULL,
  "checkin" TEXT NOT NULL,
  "checkout" TEXT NOT NULL,
  "guests" TEXT NOT NULL,
  "total" NUMERIC(12,2) NOT NULL,
  "expiresAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "quotes" (
  "id" TEXT PRIMARY KEY,
  "productId" TEXT NOT NULL,
  "ownerId" TEXT NOT NULL,
  "total" NUMERIC(12,2) NOT NULL,
  "expiresAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "orders" (
  "id" TEXT PRIMARY KEY,
  "accommodationId" INTEGER NOT NULL,
  "ownerId" TEXT NOT NULL,
  "quoteId" TEXT NOT NULL UNIQUE,
  "locator" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "checkin" TEXT NOT NULL,
  "checkout" TEXT NOT NULL,
  "guests" TEXT NOT NULL,
  "total" NUMERIC(12,2) NOT NULL,
  "currency" TEXT NOT NULL,
  "paymentReference" TEXT NOT NULL,
  "customer" TEXT NOT NULL,
  "createdAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "order_guests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "age" INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "idempotency_keys" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "operation" TEXT NOT NULL,
  "fingerprint" TEXT NOT NULL,
  "response" TEXT NOT NULL,
  "createdAt" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "outbox_events" (
  "id" TEXT PRIMARY KEY,
  "eventType" TEXT NOT NULL,
  "resourceId" TEXT NOT NULL,
  "timestamp" TEXT NOT NULL,
  "data" TEXT NOT NULL,
  "status" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "webhook_subscriptions" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "url" TEXT NOT NULL,
  "events" TEXT NOT NULL,
  "secret" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "audit_logs" (
  "id" TEXT PRIMARY KEY,
  "actorId" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "resourceId" TEXT NOT NULL,
  "timestamp" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "transaction_lock" (
  "id" INTEGER PRIMARY KEY,
  "version" INTEGER NOT NULL
);
ALTER TABLE "sessions" ADD CONSTRAINT "fk_sessions_userId" FOREIGN KEY ("userId") REFERENCES "users" (id) ON DELETE RESTRICT;
ALTER TABLE "accommodations" ADD CONSTRAINT "fk_accommodations_cityId" FOREIGN KEY ("cityId") REFERENCES "cities" (id) ON DELETE RESTRICT;
ALTER TABLE "room_types" ADD CONSTRAINT "fk_room_types_accommodationId" FOREIGN KEY ("accommodationId") REFERENCES "accommodations" (id) ON DELETE RESTRICT;
ALTER TABLE "rate_plans" ADD CONSTRAINT "fk_rate_plans_roomTypeId" FOREIGN KEY ("roomTypeId") REFERENCES "room_types" (id) ON DELETE RESTRICT;
ALTER TABLE "accommodation_facilities" ADD CONSTRAINT "fk_accommodation_facilities_accommodationId" FOREIGN KEY ("accommodationId") REFERENCES "accommodations" (id) ON DELETE RESTRICT;
ALTER TABLE "accommodation_facilities" ADD CONSTRAINT "fk_accommodation_facilities_facilityId" FOREIGN KEY ("facilityId") REFERENCES "facilities" (id) ON DELETE RESTRICT;
ALTER TABLE "photos" ADD CONSTRAINT "fk_photos_accommodationId" FOREIGN KEY ("accommodationId") REFERENCES "accommodations" (id) ON DELETE RESTRICT;
ALTER TABLE "reviews" ADD CONSTRAINT "fk_reviews_accommodationId" FOREIGN KEY ("accommodationId") REFERENCES "accommodations" (id) ON DELETE RESTRICT;
ALTER TABLE "availability_products" ADD CONSTRAINT "fk_availability_products_accommodationId" FOREIGN KEY ("accommodationId") REFERENCES "accommodations" (id) ON DELETE RESTRICT;
ALTER TABLE "quotes" ADD CONSTRAINT "fk_quotes_productId" FOREIGN KEY ("productId") REFERENCES "availability_products" (id) ON DELETE RESTRICT;
ALTER TABLE "quotes" ADD CONSTRAINT "fk_quotes_ownerId" FOREIGN KEY ("ownerId") REFERENCES "users" (id) ON DELETE RESTRICT;
ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_accommodationId" FOREIGN KEY ("accommodationId") REFERENCES "accommodations" (id) ON DELETE RESTRICT;
ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_ownerId" FOREIGN KEY ("ownerId") REFERENCES "users" (id) ON DELETE RESTRICT;
ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_quoteId" FOREIGN KEY ("quoteId") REFERENCES "quotes" (id) ON DELETE RESTRICT;
ALTER TABLE "order_guests" ADD CONSTRAINT "fk_order_guests_orderId" FOREIGN KEY ("orderId") REFERENCES "orders" (id) ON DELETE RESTRICT;
ALTER TABLE "idempotency_keys" ADD CONSTRAINT "fk_idempotency_keys_ownerId" FOREIGN KEY ("ownerId") REFERENCES "users" (id) ON DELETE RESTRICT;
ALTER TABLE "webhook_subscriptions" ADD CONSTRAINT "fk_webhook_subscriptions_ownerId" FOREIGN KEY ("ownerId") REFERENCES "users" (id) ON DELETE RESTRICT;
ALTER TABLE "audit_logs" ADD CONSTRAINT "fk_audit_logs_actorId" FOREIGN KEY ("actorId") REFERENCES "users" (id) ON DELETE RESTRICT;

CREATE INDEX orders_availability_idx ON orders ("accommodationId", status, checkin, checkout);
CREATE INDEX orders_owner_idx ON orders ("ownerId");
CREATE INDEX outbox_pending_idx ON outbox_events (status, timestamp);
CREATE INDEX quotes_owner_idx ON quotes ("ownerId");
CREATE UNIQUE INDEX facility_link_unique ON accommodation_facilities ("accommodationId", "facilityId");
ALTER TABLE room_types ADD CONSTRAINT room_capacity CHECK ("capacidadAdultos" > 0 AND "capacidadNinos" >= 0 AND habitaciones > 0);
ALTER TABLE rate_plans ADD CONSTRAINT positive_rate CHECK ("precioPorNoche" > 0 AND currency = 'USD');
ALTER TABLE orders ADD CONSTRAINT valid_order CHECK (checkout > checkin AND total > 0 AND status IN ('CONFIRMED','CANCELLED','PENDING'));
ALTER TABLE users ADD CONSTRAINT valid_role CHECK (role IN ('admin','customer'));
ALTER TABLE reviews ADD CONSTRAINT valid_score CHECK (score BETWEEN 0 AND 10);
INSERT INTO transaction_lock (id,version) VALUES (1,0) ON CONFLICT DO NOTHING;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "users" FROM anon, authenticated;
ALTER TABLE "sessions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "sessions" FROM anon, authenticated;
ALTER TABLE "cities" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "cities" FROM anon, authenticated;
ALTER TABLE "chains" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "chains" FROM anon, authenticated;
ALTER TABLE "accommodations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "accommodations" FROM anon, authenticated;
ALTER TABLE "room_types" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "room_types" FROM anon, authenticated;
ALTER TABLE "rate_plans" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "rate_plans" FROM anon, authenticated;
ALTER TABLE "facilities" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "facilities" FROM anon, authenticated;
ALTER TABLE "accommodation_facilities" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "accommodation_facilities" FROM anon, authenticated;
ALTER TABLE "photos" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "photos" FROM anon, authenticated;
ALTER TABLE "reviews" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "reviews" FROM anon, authenticated;
ALTER TABLE "availability_products" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "availability_products" FROM anon, authenticated;
ALTER TABLE "quotes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "quotes" FROM anon, authenticated;
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "orders" FROM anon, authenticated;
ALTER TABLE "order_guests" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "order_guests" FROM anon, authenticated;
ALTER TABLE "idempotency_keys" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "idempotency_keys" FROM anon, authenticated;
ALTER TABLE "outbox_events" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "outbox_events" FROM anon, authenticated;
ALTER TABLE "webhook_subscriptions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "webhook_subscriptions" FROM anon, authenticated;
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "audit_logs" FROM anon, authenticated;
ALTER TABLE "transaction_lock" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "transaction_lock" FROM anon, authenticated;
COMMIT;
