-- Renombrado sin eliminar datos: tablas y columnas en español.
BEGIN;
ALTER TABLE "users" RENAME TO "usuarios";
ALTER TABLE "usuarios" RENAME COLUMN "email" TO "correo";
ALTER TABLE "usuarios" RENAME COLUMN "name" TO "nombre";
ALTER TABLE "usuarios" RENAME COLUMN "passwordHash" TO "hash_contrasena";
ALTER TABLE "usuarios" RENAME COLUMN "role" TO "rol";
ALTER TABLE "usuarios" RENAME COLUMN "createdAt" TO "fecha_creacion";
ALTER TABLE "sessions" RENAME TO "sesiones";
ALTER TABLE "sesiones" RENAME COLUMN "userId" TO "usuario_id";
ALTER TABLE "sesiones" RENAME COLUMN "expiresAt" TO "fecha_expiracion";
ALTER TABLE "cities" RENAME TO "ciudades";
ALTER TABLE "ciudades" RENAME COLUMN "name" TO "nombre";
ALTER TABLE "ciudades" RENAME COLUMN "country" TO "pais";
ALTER TABLE "chains" RENAME TO "cadenas_hoteleras";
ALTER TABLE "cadenas_hoteleras" RENAME COLUMN "name" TO "nombre";
ALTER TABLE "accommodations" RENAME TO "alojamientos";
ALTER TABLE "alojamientos" RENAME COLUMN "cityId" TO "ciudad_id";
ALTER TABLE "alojamientos" RENAME COLUMN "image" TO "imagen";
ALTER TABLE "alojamientos" RENAME COLUMN "published" TO "publicado";
ALTER TABLE "alojamientos" RENAME COLUMN "createdAt" TO "fecha_creacion";
ALTER TABLE "alojamientos" RENAME COLUMN "updatedAt" TO "fecha_actualizacion";
ALTER TABLE "room_types" RENAME TO "tipos_habitacion";
ALTER TABLE "tipos_habitacion" RENAME COLUMN "accommodationId" TO "alojamiento_id";
ALTER TABLE "tipos_habitacion" RENAME COLUMN "capacidadAdultos" TO "capacidad_adultos";
ALTER TABLE "tipos_habitacion" RENAME COLUMN "capacidadNinos" TO "capacidad_ninos";
ALTER TABLE "rate_plans" RENAME TO "planes_tarifarios";
ALTER TABLE "planes_tarifarios" RENAME COLUMN "roomTypeId" TO "tipo_habitacion_id";
ALTER TABLE "planes_tarifarios" RENAME COLUMN "precioPorNoche" TO "precio_por_noche";
ALTER TABLE "planes_tarifarios" RENAME COLUMN "currency" TO "moneda";
ALTER TABLE "planes_tarifarios" RENAME COLUMN "cancellation" TO "politica_cancelacion";
ALTER TABLE "facilities" RENAME TO "servicios";
ALTER TABLE "servicios" RENAME COLUMN "name" TO "nombre";
ALTER TABLE "accommodation_facilities" RENAME TO "alojamientos_servicios";
ALTER TABLE "alojamientos_servicios" RENAME COLUMN "accommodationId" TO "alojamiento_id";
ALTER TABLE "alojamientos_servicios" RENAME COLUMN "facilityId" TO "servicio_id";
ALTER TABLE "photos" RENAME TO "fotos";
ALTER TABLE "fotos" RENAME COLUMN "accommodationId" TO "alojamiento_id";
ALTER TABLE "fotos" RENAME COLUMN "caption" TO "descripcion";
ALTER TABLE "reviews" RENAME TO "resenas";
ALTER TABLE "resenas" RENAME COLUMN "accommodationId" TO "alojamiento_id";
ALTER TABLE "resenas" RENAME COLUMN "author" TO "autor";
ALTER TABLE "resenas" RENAME COLUMN "score" TO "puntuacion";
ALTER TABLE "resenas" RENAME COLUMN "comment" TO "comentario";
ALTER TABLE "resenas" RENAME COLUMN "createdAt" TO "fecha_creacion";
ALTER TABLE "availability_products" RENAME TO "productos_disponibilidad";
ALTER TABLE "productos_disponibilidad" RENAME COLUMN "accommodationId" TO "alojamiento_id";
ALTER TABLE "productos_disponibilidad" RENAME COLUMN "checkin" TO "fecha_entrada";
ALTER TABLE "productos_disponibilidad" RENAME COLUMN "checkout" TO "fecha_salida";
ALTER TABLE "productos_disponibilidad" RENAME COLUMN "guests" TO "huespedes";
ALTER TABLE "productos_disponibilidad" RENAME COLUMN "expiresAt" TO "fecha_expiracion";
ALTER TABLE "quotes" RENAME TO "cotizaciones";
ALTER TABLE "cotizaciones" RENAME COLUMN "productId" TO "producto_id";
ALTER TABLE "cotizaciones" RENAME COLUMN "ownerId" TO "propietario_id";
ALTER TABLE "cotizaciones" RENAME COLUMN "expiresAt" TO "fecha_expiracion";
ALTER TABLE "orders" RENAME TO "reservas";
ALTER TABLE "reservas" RENAME COLUMN "accommodationId" TO "alojamiento_id";
ALTER TABLE "reservas" RENAME COLUMN "ownerId" TO "propietario_id";
ALTER TABLE "reservas" RENAME COLUMN "quoteId" TO "cotizacion_id";
ALTER TABLE "reservas" RENAME COLUMN "locator" TO "localizador";
ALTER TABLE "reservas" RENAME COLUMN "status" TO "estado";
ALTER TABLE "reservas" RENAME COLUMN "checkin" TO "fecha_entrada";
ALTER TABLE "reservas" RENAME COLUMN "checkout" TO "fecha_salida";
ALTER TABLE "reservas" RENAME COLUMN "guests" TO "huespedes";
ALTER TABLE "reservas" RENAME COLUMN "currency" TO "moneda";
ALTER TABLE "reservas" RENAME COLUMN "paymentReference" TO "referencia_pago";
ALTER TABLE "reservas" RENAME COLUMN "customer" TO "cliente";
ALTER TABLE "reservas" RENAME COLUMN "createdAt" TO "fecha_creacion";
ALTER TABLE "order_guests" RENAME TO "huespedes_reserva";
ALTER TABLE "huespedes_reserva" RENAME COLUMN "orderId" TO "reserva_id";
ALTER TABLE "huespedes_reserva" RENAME COLUMN "name" TO "nombre";
ALTER TABLE "huespedes_reserva" RENAME COLUMN "age" TO "edad";
ALTER TABLE "idempotency_keys" RENAME TO "claves_idempotencia";
ALTER TABLE "claves_idempotencia" RENAME COLUMN "ownerId" TO "propietario_id";
ALTER TABLE "claves_idempotencia" RENAME COLUMN "operation" TO "operacion";
ALTER TABLE "claves_idempotencia" RENAME COLUMN "fingerprint" TO "huella_solicitud";
ALTER TABLE "claves_idempotencia" RENAME COLUMN "response" TO "respuesta";
ALTER TABLE "claves_idempotencia" RENAME COLUMN "createdAt" TO "fecha_creacion";
ALTER TABLE "outbox_events" RENAME TO "eventos_pendientes";
ALTER TABLE "eventos_pendientes" RENAME COLUMN "eventType" TO "tipo_evento";
ALTER TABLE "eventos_pendientes" RENAME COLUMN "resourceId" TO "recurso_id";
ALTER TABLE "eventos_pendientes" RENAME COLUMN "timestamp" TO "fecha_evento";
ALTER TABLE "eventos_pendientes" RENAME COLUMN "data" TO "datos";
ALTER TABLE "eventos_pendientes" RENAME COLUMN "status" TO "estado";
ALTER TABLE "webhook_subscriptions" RENAME TO "suscripciones_webhook";
ALTER TABLE "suscripciones_webhook" RENAME COLUMN "ownerId" TO "propietario_id";
ALTER TABLE "suscripciones_webhook" RENAME COLUMN "events" TO "eventos";
ALTER TABLE "suscripciones_webhook" RENAME COLUMN "secret" TO "secreto";
ALTER TABLE "audit_logs" RENAME TO "registros_auditoria";
ALTER TABLE "registros_auditoria" RENAME COLUMN "actorId" TO "actor_id";
ALTER TABLE "registros_auditoria" RENAME COLUMN "action" TO "accion";
ALTER TABLE "registros_auditoria" RENAME COLUMN "resourceId" TO "recurso_id";
ALTER TABLE "registros_auditoria" RENAME COLUMN "timestamp" TO "fecha_evento";
ALTER TABLE "transaction_lock" RENAME TO "bloqueo_transacciones";
COMMIT;
